---
version: 2

seeds:
  - name: employees
    description: a manual map of employees to customers
    columns:
      - name: employee_id
        tests:
          - unique
          - not_null
  - name: snowflake_contract_rates
    description: snowflake contract rates
